version: '2'
services:
 postgres:
  ports:
   - '5477:5432'
  networks:
   - slackconnector_ruby-net
 ruby:
  ports:
   - '3000:3000'
  networks:
   - slackconnector_ruby-net
 redis:
  ports:
   - '6379:6379'
  networks:
   - slackconnector_ruby-net

networks:
 slackconnector_ruby-net:
  external: true