version: '2'
services:
 postgres:
  build:
   context: .
   dockerfile: ./docker/postgres/Dockerfile
  env_file: .pg.env
 ruby:
  build:
   context: .
   dockerfile: ./docker/ruby/Dockerfile
  volumes:
   - ./:/home/dockeruser/project
   - /usr/local/bundle # Сюда ставятся гемы в контейнере (можно использовать как кэш)
  command:
    /bin/bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
  env_file: .ruby.env