# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1618a83a65578c8b94f77998f1d5a25b9af7e038d1c359fdb5092c27b9ebb8c8a1922a1b4dd278abc05c757bb60995b59274f78c51af1baf39078c78ecc0bab0

test:
  secret_key_base: 2c13cd88da6610010255981aa30e898fce15494073da2eb138949742d1982c228616965be94901b0d73597408bae2f5606e35889b25e870e3bfcba3bae877e55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
